import {HIGHLIGHT_COLOR} from '../constants/highlight_colors'

export const books = [
	{
		id: '1',
		name: 'Code Complete 2nd Edition',
		cover: 'code_complete.jpg',
		highlights: 12,
		progress: 60,
		category: 'Tech',
		lastRead: 'October 18, 2017',
		onPage: 212,
		totalPages: 600,
	},
	{
		id: '2',
		name: 'Designing Data Intensive Applications',
		cover: 'data_intensive.jpg',
		highlights: 12,
		progress: 60,
		category: 'Tech',
		lastRead: 'October 18, 2017',
		onPage: 212,
		totalPages: 600,
	},
	{
		id: '3',
		name: "Don't Make Me Think",
		cover: 'dont_make_me_think.jpg',
		highlights: 12,
		progress: 60,
		category: 'Design',
		lastRead: 'October 18, 2017',
		onPage: 212,
		totalPages: 600,
	},
	{
		id: '4',
		name: 'Design of Everyday Things',
		cover: 'everyday_things.png',
		highlights: 12,
		progress: 60,
		category: 'Design',
		lastRead: 'October 18, 2017',
		onPage: 212,
		totalPages: 600,
	},
	{
		id: '5',
		name: 'To Kill a Mocking Bird',
		cover: 'mocking_bird.jpg',
		highlights: 12,
		progress: 60,
		category: 'Fiction',
		lastRead: 'October 18, 2017',
		onPage: 212,
		totalPages: 600,
	},
	{
		id: '6',
		name: 'White Tiger',
		cover: 'white_tiger.jpg',
		highlights: 12,
		progress: 60,
		category: 'Autobiography',
		lastRead: 'October 18, 2017',
		onPage: 212,
		totalPages: 600,
	},
]

export const highlights = [
	{
		color: HIGHLIGHT_COLOR.GREEN,
		text: 'Lorem ipsum , lorem ipsum important. Bievenue. Bonjour ca va',
		note: 'NoSQL and SQL convergence overtime',
		date: 'Today',
		location: 'Page 82',
		name: 'Design of Everyday Things',
		cover: 'code_complete.jpg',
	},
	{
		color: HIGHLIGHT_COLOR.ROSE,
		text: 'Lorem ipsum , lorem ipsum important. Bievenue. Bonjour ca va',
		note: 'Greetings',
		date: 'Today',
		location: 'Page 82',
		name: 'Design of Everyday Things',
		cover: 'code_complete.jpg',
	},
	{
		color: HIGHLIGHT_COLOR.YELLOW,
		text: 'Lorem ipsum , lorem ipsum important. Bievenue. Bonjour ca va',
		note: 'Greetings',
		date: 'Today',
		location: 'Page 82',
		name: 'Design of Everyday Things',
		cover: 'code_complete.jpg',
	},
	{
		color: HIGHLIGHT_COLOR.MAGENTA,
		text: 'Lorem ipsum , lorem ipsum important. Bievenue. Bonjour ca va',
		note: 'Greetings',
		date: 'Today',
		location: 'Page 82',
		name: 'Design of Everyday Things',
		cover: 'code_complete.jpg',
	},
	{
		color: HIGHLIGHT_COLOR.PURPLE,
		text: 'Lorem ipsum , lorem ipsum important. Bievenue. Bonjour ca va',
		note: 'Greetings',
		date: 'Today',
		location: 'Page 82',
		name: 'Design of Everyday Things',
		cover: 'code_complete.jpg',
	},
	{
		color: HIGHLIGHT_COLOR.ORANGE,
		text: `Lorem ipsum , lorem ipsum important. Bievenue. Bonjour ca va,
            Lorem ipsum , lorem ipsum important. Bievenue. Bonjour ca va,
            Lorem ipsum , lorem ipsum important. Bievenue. Bonjour ca va`,
		note: 'Greetings',
		date: 'Today',
		location: 'Page 82',
		name: 'Design of Everyday Things',
		cover: 'code_complete.jpg',
	},
	{
		color: HIGHLIGHT_COLOR.ORANGE,
		text: `Lorem ipsum , lorem ipsum important. Bievenue. Bonjour ca va,
            Lorem ipsum , lorem ipsum important. Bievenue. Bonjour ca va,
            Lorem ipsum , lorem ipsum important. Bievenue. Bonjour ca va`,
		note: 'Greetings',
		date: 'Today',
		location: 'Page 82',
		name: 'Design of Everyday Things',
		cover: 'code_complete.jpg',
	},
	{
		color: HIGHLIGHT_COLOR.PURPLE,
		text: 'Lorem ipsum , lorem ipsum important. Bievenue. Bonjour ca va',
		note: 'Greetings',
		date: 'Today',
		location: 'Page 82',
		name: 'Design of Everyday Things',
		cover: 'code_complete.jpg',
	},
	{
		color: HIGHLIGHT_COLOR.PURPLE,
		text: 'Lorem ipsum , lorem ipsum important. Bievenue. Bonjour ca va',
		note: 'Greetings',
		date: 'Today',
		location: 'Page 82',
		name: 'Design of Everyday Things',
		cover: 'code_complete.jpg',
	},
	{
		color: HIGHLIGHT_COLOR.PURPLE,
		text: 'Lorem ipsum , lorem ipsum important. Bievenue. Bonjour ca va',
		note: 'Greetings',
		date: 'Today',
		location: 'Page 82',
		name: 'Design of Everyday Things',
		cover: 'code_complete.jpg',
	},
	{
		color: HIGHLIGHT_COLOR.PURPLE,
		text: 'Lorem ipsum , lorem ipsum important. Bievenue. Bonjour ca va',
		note: 'Greetings',
		date: 'Today',
		location: 'Page 82',
		name: 'Design of Everyday Things',
		cover: 'code_complete.jpg',
	},
	{
		color: HIGHLIGHT_COLOR.PURPLE,
		text: 'Lorem ipsum , lorem ipsum important. Bievenue. Bonjour ca va',
		note: 'Greetings',
		date: 'Today',
		location: 'Page 82',
		name: 'Design of Everyday Things',
		cover: 'code_complete.jpg',
	},
	{
		color: HIGHLIGHT_COLOR.PURPLE,
		text: 'Lorem ipsum , lorem ipsum important. Bievenue. Bonjour ca va',
		note: 'Greetings',
		date: 'Today',
		location: 'Page 82',
		name: 'Design of Everyday Things',
		cover: 'code_complete.jpg',
	},
	{
		color: HIGHLIGHT_COLOR.PURPLE,
		text: 'Lorem ipsum , lorem ipsum important. Bievenue. Bonjour ca va',
		note: 'Greetings',
		date: 'Today',
		location: 'Page 82',
		name: 'Design of Everyday Things',
		cover: 'code_complete.jpg',
	},
	{
		color: HIGHLIGHT_COLOR.PURPLE,
		text: 'Lorem ipsum , lorem ipsum important. Bievenue. Bonjour ca va',
		note: 'Greetings',
		date: 'Today',
		location: 'Page 82',
		name: 'Design of Everyday Things',
		cover: 'code_complete.jpg',
	},
]
